name: Toolchain build

# The ci-* tags and what they build are documented in the top-level repo:
# https://github.com/AmigaPorts/m68k-amigaos-gcc/blob/master/.github/workflows/toolchain.yml
on:
  pull_request:
    types: [labeled]

jobs:
  toolchain:
    if: startsWith(github.event.label.name, 'ci-')
    uses: AmigaPorts/m68k-amigaos-gcc/.github/workflows/toolchain.yml@master
    with:
      checkout_repo: AmigaPorts/m68k-amigaos-gcc
      checkout_ref: master
      repos: sfdc=${{ github.event.pull_request.head.repo.clone_url }}#${{ github.event.pull_request.head.sha }}
